import { useState } from "react";
import { Copy, Check, Eye, EyeOff } from "lucide-react";
import { useLanguage } from "../../utils/LanguageContext";
import { SessionManagementSection } from "../SessionManagementSection";

interface SettingsProps {}

/**
 * Settings page component for managing API keys and preferences.
 * Displays project API key (read-only, cannot be regenerated by user).
 * 
 * @param {SettingsProps} props - Component properties (unused)
 * @returns {JSX.Element} The settings page layout
 */
export function Settings({}: SettingsProps) {
    const { t, language, setLanguage } = useLanguage();
    
    /**
     * Gets the current project's API key from localStorage.
     * 
     * @returns {string | null} Project API key or null
     */
    const getProjectApiKey = (): string | null => {
        const projectsData = localStorage.getItem("projects");
        const activeProjectId = localStorage.getItem("active_project_id");
        
        if (!projectsData || !activeProjectId) {
            return null;
        }
        
        try {
            const projects = JSON.parse(projectsData);
            const activeProject = projects.find(
                (p: { id: number }) => p.id === parseInt(activeProjectId)
            );
            return activeProject?.apiKey || null;
        } catch {
            return null;
        }
    };
    
    const [apiKey] = useState<string | null>(getProjectApiKey());
    const [isActive] = useState(true);
    const [copied, setCopied] = useState(false);
    const [showKey, setShowKey] = useState(false);
    const [refreshInterval, setRefreshInterval] = useState(5);
    const [alertThreshold, setAlertThreshold] = useState(0.70);
    const [dataRetention, setDataRetention] = useState(30);
    const [tempRefreshInterval, setTempRefreshInterval] = useState(5);
    const [tempAlertThreshold, setTempAlertThreshold] = useState(0.70);
    const [tempDataRetention, setTempDataRetention] = useState(30);
    const [isEditingRefresh, setIsEditingRefresh] = useState(false);
    const [isEditingThreshold, setIsEditingThreshold] = useState(false);
    const [isEditingRetention, setIsEditingRetention] = useState(false);
    const [tempRefresh, setTempRefresh] = useState("");
    const [tempThreshold, setTempThreshold] = useState("");
    const [tempRetention, setTempRetention] = useState("");
    const [hasChanges, setHasChanges] = useState(false);

    /**
     * Copies the API key to clipboard.
     * 
     * @returns {Promise<void>}
     */
    const handleCopyKey = async (): Promise<void> => {
        if (apiKey) {
            await navigator.clipboard.writeText(apiKey);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    /**
     * Toggles language between English and Korean.
     * 
     * @returns {void}
     */
    const handleLanguageToggle = (): void => {
        setLanguage(language === "en" ? "ko" : "en");
    };

    /**
     * Starts editing refresh interval value.
     * 
     * @returns {void}
     */
    const startEditingRefresh = (): void => {
        setIsEditingRefresh(true);
        setTempRefresh(refreshInterval.toString());
    };

    /**
     * Saves the edited refresh interval value.
     * 
     * @returns {void}
     */
    const saveRefreshInterval = (): void => {
        const value = parseInt(tempRefresh);
        if (!isNaN(value) && value >= 1 && value <= 30) {
            setTempRefreshInterval(value);
            setHasChanges(true);
        }
        setIsEditingRefresh(false);
    };

    /**
     * Starts editing alert threshold value.
     * 
     * @returns {void}
     */
    const startEditingThreshold = (): void => {
        setIsEditingThreshold(true);
        setTempThreshold(tempAlertThreshold.toFixed(2));
    };

    /**
     * Saves the edited alert threshold value.
     * 
     * @returns {void}
     */
    const saveAlertThreshold = (): void => {
        const value = parseFloat(tempThreshold);
        if (!isNaN(value) && value >= 0.1 && value <= 1.0) {
            setTempAlertThreshold(value);
            setHasChanges(true);
        }
        setIsEditingThreshold(false);
    };

    /**
     * Starts editing data retention value.
     * 
     * @returns {void}
     */
    const startEditingRetention = (): void => {
        setIsEditingRetention(true);
        setTempRetention(tempDataRetention.toString());
    };

    /**
     * Saves the edited data retention value.
     * 
     * @returns {void}
     */
    const saveDataRetention = (): void => {
        const value = parseInt(tempRetention);
        if (!isNaN(value) && value >= 7 && value <= 365) {
            setTempDataRetention(value);
            setHasChanges(true);
        }
        setIsEditingRetention(false);
    };

    /**
     * Applies all preference changes.
     * 
     * @returns {void}
     */
    const handleApplyChanges = (): void => {
        setRefreshInterval(tempRefreshInterval);
        setAlertThreshold(tempAlertThreshold);
        setDataRetention(tempDataRetention);
        setHasChanges(false);
    };

    /**
     * Resets preferences to applied values.
     * 
     * @returns {void}
     */
    const handleResetChanges = (): void => {
        setTempRefreshInterval(refreshInterval);
        setTempAlertThreshold(alertThreshold);
        setTempDataRetention(dataRetention);
        setHasChanges(false);
    };

    /**
     * Renders the page header.
     * 
     * @returns {JSX.Element} Header section
     */
    const renderHeader = (): JSX.Element => {
        return (
            <div className="mb-4 pb-3 border-b border-gray-800">
                <h1 className="text-lg text-white">
                    {t("settings")}
                </h1>
                <p className="text-gray-600 text-[10px] mt-0.5">
                    Manage API keys and system preferences
                </p>
            </div>
        );
    };

    /**
     * Renders the API key management section.
     * 
     * @returns {JSX.Element} API key section
     */
    const renderApiKeySection = (): JSX.Element => {
        const maskedKey = apiKey 
            ? `${apiKey.substring(0, 12)}${"*".repeat(apiKey.length - 12)}`
            : "";

        return (
            <div className="bg-gray-900 border border-gray-800 p-3">
                <h3 className="text-[11px] text-gray-500 uppercase 
                    tracking-wider mb-3 pb-2 border-b border-gray-800">
                    {t("apiKeyManagement")}
                </h3>

                {apiKey ? (
                    <div className="space-y-3">
                        <div>
                            <label className="text-[10px] text-gray-600 
                                uppercase block mb-1.5">
                                {t("currentApiKey")}
                            </label>
                            <div className="flex items-center gap-2">
                                <div className="flex-1 bg-black border 
                                    border-gray-800 px-2 py-1.5 
                                    font-mono text-xs text-gray-400">
                                    {showKey ? apiKey : maskedKey}
                                </div>
                                <button
                                    onClick={() => setShowKey(!showKey)}
                                    className="bg-gray-800 border 
                                        border-gray-700 p-1.5 
                                        text-gray-500 hover:text-gray-400 
                                        hover:bg-gray-700 transition-colors"
                                    title={showKey ? "Hide" : "Show"}
                                >
                                    {showKey ? (
                                        <EyeOff className="w-3 h-3" />
                                    ) : (
                                        <Eye className="w-3 h-3" />
                                    )}
                                </button>
                            </div>
                        </div>

                        <div>
                            <button
                                onClick={handleCopyKey}
                                className="w-full bg-gray-800 border 
                                    border-gray-700 px-3 py-1.5 
                                    text-gray-400 hover:text-gray-300 
                                    hover:bg-gray-700 transition-colors 
                                    text-xs flex items-center 
                                    justify-center gap-1.5"
                            >
                                {copied ? (
                                    <>
                                        <Check className="w-3 h-3" />
                                        {t("copied")}
                                    </>
                                ) : (
                                    <>
                                        <Copy className="w-3 h-3" />
                                        {t("copyKey")}
                                    </>
                                )}
                            </button>
                        </div>

                        <div className="pt-2 border-t border-gray-800">
                            <div className="flex items-center 
                                justify-between py-1">
                                <span className="text-[10px] text-gray-600 
                                    uppercase">
                                    Status
                                </span>
                                <span className={`text-xs 
                                    ${isActive ? "text-green-500" : "text-gray-500"}`}>
                                    {isActive ? "Active" : "Inactive"}
                                </span>
                            </div>
                            <div className="pt-2 mt-2 border-t 
                                border-gray-800">
                                <p className="text-[9px] text-gray-600">
                                    This API key is unique to your project 
                                    and cannot be regenerated by users. 
                                    Contact your administrator if you need 
                                    a new key.
                                </p>
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="text-center py-6">
                        <p className="text-gray-600 text-xs mb-3">
                            No API key available. Please select a project 
                            from the project list.
                        </p>
                    </div>
                )}
            </div>
        );
    };

    /**
     * Renders the preferences section.
     * 
     * @returns {JSX.Element} Preferences section
     */
    const renderPreferencesSection = (): JSX.Element => {
        return (
            <div className="bg-gray-900 border border-gray-800 p-3">
                <h3 className="text-[11px] text-gray-500 uppercase 
                    tracking-wider mb-3 pb-2 border-b border-gray-800">
                    {t("preferences")}
                </h3>

                <div className="space-y-3">
                    <div className="flex items-center justify-between \n                        py-1.5 border-b border-gray-800">
                        <div className="flex-1">
                            <p className="text-[10px] text-gray-600 \n                                uppercase">
                                {t("language")}
                            </p>
                            <p className="text-[10px] text-gray-700 mt-0.5">
                                {t("interfaceLanguage")}
                            </p>
                        </div>
                        <div className="w-48 flex justify-end">
                            <button
                                onClick={handleLanguageToggle}
                                className="bg-gray-800 border border-gray-700 \n                                    px-3 py-1.5 text-gray-400 \n                                    hover:text-gray-300 hover:bg-gray-700 \n                                    transition-colors text-xs"
                            >
                                {language === "en" ? "English" : "한국어"}
                            </button>
                        </div>
                    </div>

                    <div className="flex items-center justify-between \n                        py-1.5 border-b border-gray-800">
                        <div className="flex-1">
                            <p className="text-[10px] text-gray-600 \n                                uppercase">
                                {t("autoRefresh")}
                            </p>
                            <p className="text-[10px] text-gray-700 mt-0.5">
                                {t("dashboardUpdateInterval")}
                            </p>
                        </div>
                        <div className="w-48 flex items-center justify-end gap-2">
                            <input
                                type="range"
                                min="1"
                                max="30"
                                value={tempRefreshInterval}
                                onChange={(e) => {
                                    setTempRefreshInterval(Number(e.target.value));
                                    setHasChanges(true);
                                }}
                                className="w-32 h-1 bg-gray-700 rounded-lg \n                                    appearance-none cursor-pointer \n                                    accent-teal-500"
                            />
                            {isEditingRefresh ? (
                                <input
                                    type="text"
                                    value={tempRefresh}
                                    onChange={(e) => setTempRefresh(e.target.value)}
                                    onBlur={saveRefreshInterval}
                                    onKeyDown={(e) => {
                                        if (e.key === "Enter") saveRefreshInterval();
                                        if (e.key === "Escape") setIsEditingRefresh(false);
                                    }}
                                    autoFocus
                                    className="w-12 text-xs text-gray-300 \n                                        font-mono text-right bg-gray-800 \n                                        border border-teal-500 px-1 py-0.5 \n                                        focus:outline-none"
                                />
                            ) : (
                                <span 
                                    onClick={startEditingRefresh}
                                    className="text-xs text-gray-400 \n                                        font-mono w-12 text-right cursor-pointer \n                                        hover:text-teal-400 transition-colors"
                                >
                                    {tempRefreshInterval}s
                                </span>
                            )}
                        </div>
                    </div>

                    <div className="flex items-center justify-between \n                        py-1.5 border-b border-gray-800">
                        <div className="flex-1">
                            <p className="text-[10px] text-gray-600 \n                                uppercase">
                                {t("alertThreshold")}
                            </p>
                            <p className="text-[10px] text-gray-700 mt-0.5">
                                {t("minimumScoreForAlerts")}
                            </p>
                        </div>
                        <div className="w-48 flex items-center justify-end gap-2">
                            <input
                                type="range"
                                min="0.1"
                                max="1.0"
                                step="0.05"
                                value={tempAlertThreshold}
                                onChange={(e) => {
                                    setTempAlertThreshold(Number(e.target.value));
                                    setHasChanges(true);
                                }}
                                className="w-32 h-1 bg-gray-700 rounded-lg \n                                    appearance-none cursor-pointer \n                                    accent-teal-500"
                            />
                            {isEditingThreshold ? (
                                <input
                                    type="text"
                                    value={tempThreshold}
                                    onChange={(e) => setTempThreshold(e.target.value)}
                                    onBlur={saveAlertThreshold}
                                    onKeyDown={(e) => {
                                        if (e.key === "Enter") saveAlertThreshold();
                                        if (e.key === "Escape") setIsEditingThreshold(false);
                                    }}
                                    autoFocus
                                    className="w-12 text-xs text-gray-300 \n                                        font-mono text-right bg-gray-800 \n                                        border border-teal-500 px-1 py-0.5 \n                                        focus:outline-none"
                                />
                            ) : (
                                <span 
                                    onClick={startEditingThreshold}
                                    className="text-xs text-gray-400 \n                                        font-mono w-12 text-right cursor-pointer \n                                        hover:text-teal-400 transition-colors"
                                >
                                    {tempAlertThreshold.toFixed(2)}
                                </span>
                            )}
                        </div>
                    </div>

                    <div className="flex items-center justify-between py-1.5">
                        <div className="flex-1">
                            <p className="text-[10px] text-gray-600 \n                                uppercase">
                                {t("dataRetention")}
                            </p>
                            <p className="text-[10px] text-gray-700 mt-0.5">
                                {t("alertHistoryDuration")}
                            </p>
                        </div>
                        <div className="w-48 flex items-center justify-end gap-2">
                            <input
                                type="range"
                                min="7"
                                max="365"
                                step="1"
                                value={tempDataRetention}
                                onChange={(e) => {
                                    setTempDataRetention(Number(e.target.value));
                                    setHasChanges(true);
                                }}
                                className="w-32 h-1 bg-gray-700 rounded-lg 
                                    appearance-none cursor-pointer 
                                    accent-teal-500"
                            />
                            {isEditingRetention ? (
                                <input
                                    type="text"
                                    value={tempRetention}
                                    onChange={(e) => setTempRetention(e.target.value)}
                                    onBlur={saveDataRetention}
                                    onKeyDown={(e) => {
                                        if (e.key === "Enter") saveDataRetention();
                                        if (e.key === "Escape") setIsEditingRetention(false);
                                    }}
                                    autoFocus
                                    className="w-12 text-xs text-gray-300 
                                        font-mono text-right bg-gray-800 
                                        border border-teal-500 px-1 py-0.5 
                                        focus:outline-none"
                                />
                            ) : (
                                <span 
                                    onClick={startEditingRetention}
                                    className="text-xs text-gray-400 
                                        font-mono w-12 text-right cursor-pointer 
                                        hover:text-teal-400 transition-colors"
                                >
                                    {tempDataRetention}{language === "ko" ? "일" : "d"}
                                </span>
                            )}
                        </div>
                    </div>
                </div>

                <div className="flex items-center justify-between mt-4">
                    <button
                        onClick={handleResetChanges}
                        className="bg-gray-800 border border-gray-700 
                            px-4 py-2 text-gray-400 hover:text-gray-300 
                            hover:bg-gray-700 transition-colors text-xs"
                    >
                        {t("reset")}
                    </button>
                    <button
                        onClick={handleApplyChanges}
                        className="bg-gray-800 border border-gray-700 
                            px-4 py-2 text-gray-400 hover:text-gray-300 
                            hover:bg-gray-700 transition-colors text-xs"
                        disabled={!hasChanges}
                    >
                        {t("apply")}
                    </button>
                </div>
            </div>
        );
    };

    return (
        <div>
            {renderHeader()}
            <div className="grid grid-cols-2 gap-3 mb-3">
                <div>
                    {renderApiKeySection()}
                </div>
                <div>
                    {renderPreferencesSection()}
                </div>
            </div>
            <SessionManagementSection />
        </div>
    );
}
